CREATE OR REPLACE TABLE INGREDIENTE (
ID LONG NOT NULL,
SKU VARCHAR NOT NULL,
NOMBRE VARCHAR NOT NULL,
DESCRIPCION VARCHAR NOT NULL,
STATUS BOOLEAN NOT NULL,
CONSTRAINT INGREDIENTE_ID_PK PRIMARY KEY(ID)
);